# remove conflict with vim keybinds
map ctrl+shift+h no_op
map ctrl+shift+l no_op

# map ctrl+shift+left no_op
# map ctrl+shift+right no_op

# send C-. and C-` as CSI u sequences (fixes these keys inside tmux)
map ctrl+period send_text all \x1b[46;5u
map ctrl+grave_accent send_text all \x1b[96;5u


allow_remote_control yes

# open new windows/tabs/OS windows in the same working directory
map cmd+enter        new_window_with_cwd
map cmd+t            new_tab_with_cwd
map cmd+n            new_os_window_with_cwd

# send terminal contents to a pager
map ctrl+shift+f launch --stdin-source=@screen_scrollback --stdin-add-formatting=false --type=overlay nvim 

# Fonts
font_family      JetBrains Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        12.0

# Tab bar
tab_bar_style                powerline
tab_powerline_style          slanted
tab_bar_min_tabs             2
tab_title_template           " {index}: {title} "
active_tab_font_style        bold
inactive_tab_font_style      normal
active_tab_foreground        #1e1e2e
active_tab_background        #cdd6f4
inactive_tab_foreground      #6c7086
inactive_tab_background      #313244
tab_bar_background           #181825
